kind: pipeline
name: code-analyze-check
type: kubernetes

trigger:
  branch: master
  event:
    - push
steps:
  - name: build
    pull: if-not-exists
    image: node:12.18.4-buster
    commands:
      - node -v
      - cat trigger.txt
      - curl https://github.com/XGovFormBuilder/digital-form-builder/tree/master/designer/package.json -o designer.json
      - export DESIGNER_VERSION=$(node -e "console.log(require('./designer.json').version);")
      - echo $DESIGNER_VERSION
      - curl https://github.com/XGovFormBuilder/digital-form-builder/tree/master/runner/package.json -o runner.json
      - export RUNNER_VERSION=$(node -e "console.log(require('./runner.json').version);")
      - echo $RUNNER_VERSION
      - ls -lah
    when:
      branch:
        - master
      event:
        - push