kind: pipeline
name: designer
type: kubernetes
trigger:
  branch: main
  event:
    - push
    - tag
steps:
  - name: checkout code from xgov
    image: alpine/git
    commands:
      - git clone https://github.com/XGovFormBuilder/digital-form-builder/
      -  bin/env.sh
  - name: setup tags
    pull: if-not-exists
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    commands:
      -  bin/env.sh
    depends_on:
      - checkout code from xgov
  - name: ecr-login
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/dind-awscli:19.03.12-dind-1.18.55
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: DESIGNER_REGISTRY_AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: DESIGNER_REGISTRY_AWS_SECRET_ACCESS_KEY
      AWS_REGION: eu-west-2
    commands:
      - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
      - aws ecr get-login-password --region $${AWS_REGION} | docker login --username AWS --password-stdin 340268328991.dkr.ecr.$${AWS_REGION}.amazonaws.com
    volumes:
      - name: dockerclientconfig
        path: /root/.docker
    depends_on:
      - setup tags
  - name: build docker tag
    pull: if-not-exists
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    commands:
      - bin/env.sh
      - source .env
      - echo "docker build --build-arg BASE_IMAGE_TAG=$${BASE_IMAGE_TAG}"
      - docker build --build-arg BASE_IMAGE_TAG=$${BASE_IMAGE_TAG} -t forms-designer:$${DRONE_COMMIT_SHA} -t forms-designer:latest designer/. --no-cache
    volumes:
      - name: dockerclientconfig
        path: /root/.docker
    depends_on:
      - setup tags
  - name: publish
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/dind-awscli:19.03.12-dind-1.18.55
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: DESIGNER_REGISTRY_AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: DESIGNER_REGISTRY_AWS_SECRET_ACCESS_KEY
      AWS_REGION: eu-west-2
    commands:
      - echo "Publish"
      - docker build --build-arg BASE_IMAGE_TAG=$${BASE_IMAGE_TAG} -t forms-designer:$${DRONE_COMMIT_SHA} -t forms-designer:latest designer/. --no-cache
      - docker image push 340268328991.dkr.ecr.$${AWS_REGION}.amazonaws.com/stp/forms-designer:$${BASE_IMAGE_TAG}
      - docker image push 340268328991.dkr.ecr.$${AWS_REGION}.amazonaws.com/stp/forms-designer:$${DRONE_COMMIT_SHA}
      - docker image push 340268328991.dkr.ecr.$${AWS_REGION}.amazonaws.com/stp/forms-designer:latest
    volumes:
      - name: dockerclientconfig
        path: /root/.docker
    depends_on:
      - build docker tag
  - name: trigger dev deploy
    image: plugins/downstream
    settings:
      server: https://drone-gh.acp.homeoffice.gov.uk/
      deploy: development
      fork: true
      token:
        from_secret: downstream-trigger-token
      params:
        - SOURCE_HASH=${DRONE_COMMIT_HASH}
        - APP=digital-form-builder-designer
        - /drone/src/.env
      last_successful: true
      repositories:
        - UKHomeOffice/digital-form-builder-acp-deploy@main
    depends_on:
      - publish
services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

volumes:
  - name: dockerclientconfig
    temp: {}