kind: pipeline
name: designer
type: kubernetes
trigger:
  branch: main
  event:
    - push
    - tag
steps:
  - name: checkout code from xgov
    image: alpine/git
    commands:
      - git clone https://github.com/XGovFormBuilder/digital-form-builder/
      - source .env
      - cd digital-form-builder
      - git checkout $XGOV_SHA
      - cd ..
    volumes:
      - name: dockerclientconfig
        path: /root/.docker
  - name: setup tags
    pull: if-not-exists
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    commands:
      -  bin/env.sh
    volumes:
      - name: dockerclientconfig
        path: /root/.docker
    depends_on:
      - checkout code from xgov
  - name: print setup
    pull: if-not-exists
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    commands:
      - echo $BASE_IMAGE_VERSION
    volumes:
      - name: dockerclientconfig
        path: /root/.docker
    depends_on:
      - setup tags
  - name: publish to ecr
    image: plugins/ecr
    settings:
      access_key:
        from_secret: DESIGNER_REGISTRY_AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: DESIGNER_REGISTRY_AWS_SECRET_ACCESS_KEY
      region: eu-west-2
      repo: stp/forms-designer
      registry: 340268328991.dkr.ecr.eu-west-2.amazonaws.com
      dockerfile: designer/Dockerfile
      build_args:
        - BASE_IMAGE_TAG=${BASE_IMAGE_VERSION}
      tags:
        - ${DRONE_COMMIT_SHA}
        - latest
    volumes:
      - name: dockerclientconfig
        path: /root/.docker
    depends_on:
      - print setup
  - name: list tags
    pull: if-not-exists
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    commands:
      - docker image search --list-tags 340268328991.dkr.ecr.eu-west-2.amazonaws.com/stp/forms-designer
    depends_on:
      - publish to ecr
  - name: trigger dev deploy
    image: plugins/downstream
    settings:
      server: https://drone-gh.acp.homeoffice.gov.uk/
      deploy: development
      fork: true
      token:
        from_secret: downstream-trigger-token
      params:
        - SOURCE_HASH=${DRONE_COMMIT_HASH}
        - APP=digital-form-builder-designer
        - /drone/src/.env
      last_successful: true
      repositories:
        - UKHomeOffice/digital-form-builder-acp-deploy@main
    depends_on:
      - build docker tag
services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

volumes:
  - name: dockerclientconfig
    temp: {}
