kind: pipeline
name: code-analyze-check
type: kubernetes

trigger:
  branch: main
  event:
    - push
    - tag
steps:
  - name: extact meta data for XGovFormBuilder
    pull: if-not-exists
    image: alpine/git
    commands:
      - cat trigger.txt
      - export sha=$(tail -1 trigger.txt)
      - echo "Current SHA is $sha from trigger"
      - git clone https://github.com/XGovFormBuilder/digital-form-builder/
      - cd digital-form-builder
      - git log -1
      - export LAST_COMMIT_AUTHOR=$(echo $(git log -1 --pretty=format:"%an"))
      - export LAST_COMMIT_AUTHOR_EMAIL=$(echo $(git log -1 --pretty=format:"%ae"))
      - export LAST_COMMIT_MESSAGE=$(echo $(git log -1 --pretty='%s%d [%an]'))
      - echo XGOV_TAG=1.0.0 > .env
      - echo 1.0.0 > .tags
      - echo "Processing $LAST_COMMIT_MESSAGE $LAST_COMMIT_AUTHOR $LAST_COMMIT_AUTHOR_EMAIL"
      - git describe --tags
      - echo "Drone Env :$${DRONE_COMMIT_REF} $${DRONE_COMMIT_SHA} $${DRONE_COMMIT_LINK} $${DRONE_COMMIT_MESSAGE} $${DRONE_COMMIT_AUTHOR} $${DRONE_COMMIT_AUTHOR_EMAIL} $${DRONE_COMMIT_AUTHOR_NAME}"
    environment:
      XGOV_AUTHOR: $${LAST_COMMIT_AUTHOR}
      XGOV_AUTHOR_EMAIL: $${LAST_COMMIT_AUTHOR_EMAIL}
      XGOV_COMMIT_MESSAGE: $${LAST_COMMIT_MESSAGE}
      XGOV_TAG: 1.0.0
    volumes:
      - name: dockerclientconfig
        path: /root/.docker
    when:
      branch:
        - main
      event:
        - push
        - tag
volumes:
  - name: dockerclientconfig
    temp: {}
---
kind: pipeline
name: designer
type: kubernetes
trigger:
  branch: main
  event:
    - push
clone:
  disable: true
steps:
  - name: setup tags
    pull: if-not-exists
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    commands:
      - source .env
      - env
      - echo "Current SHA is $${BRANCH} $${DRONE_COMMIT} $${DRONE_COMMIT_AFTER} $${DRONE_COMMIT_AUTHOR} $${DRONE_COMMIT_AUTHOR_AVATAR} $${DRONE_COMMIT_AUTHOR_EMAIL} $${DRONE_COMMIT_AUTHOR_NAME}"
      - export TAG_VERSION=$(tail -1 trigger.txt)
      - echo $${XGOV_TAG}
      - echo "$${TAG_VERSION}" > .tags
    volumes:
      - name: dockerclientconfig
        path: /root/.docker
  - name: build docker tag
    pull: if-not-exists
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    commands:
      - export TAG_VERSION=$(cat .tags)
      - echo " TAG - $TAG_VERSION"
      - docker build -t digital-form-builder-designer:$TAG_VERSION -t digital-form-builder-designer:$DRONE_COMMIT_SHA -t digital-form-builder-designer:latest ./docker/designer/. --no-cache
    when:
      branch:
        - main
      event:
        - push
    volumes:
      - name: dockerclientconfig
        path: /root/.docker
    depends_on:
      - setup tags
  - name: anchore scan
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
    pull: always
    environment:
      IMAGE_NAME: stp/fco-form-builder-designer:${DRONE_COMMIT_SHA}
    depends_on:
      - build docker tag
  - name: ecr-login
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/dind-awscli:19.03.12-dind-1.18.55
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: DESIGNER_AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: DESIGNER_AWS_SECRET_ACCESS_KEY
      AWS_REGION: eu-west-2
    commands:
      - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
      - aws ecr get-login-password --region $${AWS_REGION} | docker login --username AWS --password-stdin 340268328991.dkr.ecr.$${AWS_REGION}.amazonaws.com
    volumes:
      - name: dockerclientconfig
        path: /root/.docker
    depends_on:
      - anchore scan
depends_on:
  - code-analyze-check


services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  
  - name: anchore-submission-server
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
    pull: always
    commands:
      - /run.sh server

volumes:
  - name: dockerclientconfig
    temp: {}