kind: pipeline
name: designer
type: kubernetes
trigger:
  branch: anchore-scan
  event:
    - push
steps:
  - name: setup tags
    pull: if-not-exists
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    commands:
      - bin/designer.sh
  - name: publish to ecr
    image: plugins/ecr
    settings:
      access_key:
        from_secret: DESIGNER_REGISTRY_AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: DESIGNER_REGISTRY_AWS_SECRET_ACCESS_KEY
      region: eu-west-2
      repo: stp/forms-designer
      registry: 340268328991.dkr.ecr.eu-west-2.amazonaws.com
      dockerfile: designer/Dockerfile.out
    depends_on:
      - setup tags
    when:
      branch: anchore-scan
      event:
        - push
  - name: pull image
    pull: if-not-exists
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    commands:
      - docker pull 340268328991.dkr.ecr.eu-west-2.amazonaws.com/stp/forms-designer:latest
    depends_on:
      - publish to ecr
    when:
      branch: anchore-scan
      event:
        - push
  - name: scan-image
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
    pull: always
    environment:
      IMAGE_NAME: stp/forms-designer:${DRONE_COMMIT_SHA}
      DOCKER_HOST: tcp://172.17.0.1:2375
    depends_on:
      - pull image
    when:
      branch: anchore-scan
      event:
        - push


services:
  - name: anchore-submission-server
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
    pull: always
    commands:
      - /run.sh server