kind: pipeline
name: code-analyze-check
type: kubernetes

trigger:
  branch: master
  event:
    - push
steps:
  - name: build
    pull: if-not-exists
    image: node:12.18.4-buster
    commands:
      - node -v
      - echo $(git log -1)
      - cat trigger.txt
      - export sha=$(tail -1 trigger.txt)
      - git clone https://github.com/XGovFormBuilder/digital-form-builder/
      - cd digital-form-builder
      - git checkout $sha
      - git log -1
    when:
      branch:
        - master
      event:
        - push
  - name: ecr-login
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/dind-awscli:19.03.12-dind-1.18.55
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: DESIGNER_AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: DESIGNER_AWS_SECRET_ACCESS_KEY
      AWS_REGION: eu-west-2
    commands:
      - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
      - aws ecr get-login-password --region $${AWS_REGION} | docker login --username AWS --password-stdin 340268328991.dkr.ecr.$${AWS_REGION}.amazonaws.com
    volumes:
      - name: dockerclientconfig
        path: /root/.docker
      - name: setup
        pull: if-not-exists
        image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
        commands:
          - sleep 5
          - n=0; while [ "$n" -lt 120 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
          - "export TAG_VERSION=$(cat ./designer/package.json | grep version | head -1 | cut -d : -f2 | cut -d , -f1 | tr -d '\"' | tr -d ' ')"
          - echo "$${TAG_VERSION}" > .tags
        volumes:
          - name: dockerclientconfig
            path: /root/.docker
      - name: build docker tag
        pull: if-not-exists
        image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
        commands:
          - "export TAG_VERSION=$(cat .tags)"
          - echo " TAG - $TAG_VERSION"
          - docker build -t stp/fco-form-builder-designer:$TAG_VERSION -t stp/fco-form-builder-designer:$DRONE_COMMIT_SHA -t stp/fco-form-builder-designer:latest ./docker/designer/. --no-cache
        when:
          branch:
            - master
          event:
            - push
        volumes:
          - name: dockerclientconfig
            path: /root/.docker
        depends_on:
          - setup
      - name: anchore scan
        image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
        pull: always
        environment:
          IMAGE_NAME: stp/fco-form-builder-designer:${DRONE_COMMIT_SHA}
          WHITELIST: CVE-2020-7788,CVE-2020-7754,CVE-2020-7774,CVE-2017-18589,CVE-2020-15133,CVE-2020-7788,CVE-2020-7774
        depends_on:
          - build
      - name: publish
        pull: if-not-exists
        image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
        commands:
          - "export TAG_VERSION=$(cat .tags)"
          - echo " TAG - $TAG_VERSION"
          - docker image tag stp/fco-form-builder-designer:$DRONE_COMMIT_SHA 340268328991.dkr.ecr.eu-west-2.amazonaws.com/stp/fco-form-builder-designer:$DRONE_COMMIT_SHA
          - docker image tag stp/fco-form-builder-designer:$TAG_VERSION 340268328991.dkr.ecr.eu-west-2.amazonaws.com/stp/fco-form-builder-designer:$TAG_VERSION
          - docker image tag stp/fco-form-builder-designer:latest 340268328991.dkr.ecr.eu-west-2.amazonaws.com/stp/fco-form-builder-designer:latest
          - docker image push 340268328991.dkr.ecr.eu-west-2.amazonaws.com/stp/fco-form-builder-designer:$TAG_VERSION
          - docker image push 340268328991.dkr.ecr.eu-west-2.amazonaws.com/stp/fco-form-builder-designer:$DRONE_COMMIT_SHA
          - docker image push 340268328991.dkr.ecr.eu-west-2.amazonaws.com/stp/fco-form-builder-designer:latest
          - docker images --format "table {{.ID}}\t{{.Repository}}\t{{.Tag}}\t{{.Size}}"
        when:
          branch:
            - master
          event:
            - push
        volumes:
          - name: dockerclientconfig
            path: /root/.docker
        depends_on:
          - scan
      - name: deploy
        image: quay.io/ukhomeofficedigital/kd:v1.16.0
        commands:
          - apk update
          - apk add curl
          #- source bin/designer/env.sh
          #- bin/designer/deploy.sh
        environment:
          DRONE_DEPLOY_TO: acp-notprod
          IMAGE_URL: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/stp/fco-form-builder-designer$${RUNNER_TAG_VERSION}
          KUBE_NAMESPACE: stp-dev
          KUBE_TOKEN_ACP_NOTPROD:
            from_secret: kube_token_acp_notprod
          PREVIEW_MODE: true
          PREVIEW_URL: https://form-builder.dev.stp-notprod.homeoffice.gov.uk
          PUBLISH_URL: https://form-builder.dev.internal.stp-notprod.homeoffice.gov.uk
        when:
          branch:
            - master
          event:
            - push
        depends_on:
          - publish