kind: pipeline
name: designer
type: kubernetes
trigger:
  branch: main
  event:
    - push
    - tag
steps:
  - name: checkout code from xgov
    image: alpine/git
    commands:
      - git clone https://github.com/XGovFormBuilder/digital-form-builder/
  - name: ecr-login
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/dind-awscli:19.03.12-dind-1.18.55
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: DESIGNER_REGISTRY_AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: DESIGNER_REGISTRY_AWS_SECRET_ACCESS_KEY
      AWS_REGION: eu-west-2
    commands:
      - source .env
      - echo "Current XGOV tag $${XGOV_TAG}"
      - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
      - aws ecr get-login-password --region $${AWS_REGION} | docker login --username AWS --password-stdin 340268328991.dkr.ecr.$${AWS_REGION}.amazonaws.com | docker build --build-arg BASE_IMAGE_TAG=$${XGOV_TAG} -t stp/forms-designer:$${DRONE_COMMIT_SHA} -t stp/forms-designer:latest designer/. --no-cache
      - docker image push stp/forms-designer:$${DRONE_COMMIT_SHA}
    volumes:
      - name: dockerclientconfig
        path: /root/.docker
    depends_on:
      - checkout code from xgov
  - name: build and publish docker tag
    pull: if-not-exists
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: DESIGNER_REGISTRY_AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: DESIGNER_REGISTRY_AWS_SECRET_ACCESS_KEY
      AWS_REGION: eu-west-2
    commands:
      - source .env
      - echo "Current XGOV tag $${XGOV_TAG}"
      - echo "docker build --build-arg BASE_IMAGE_TAG=$${XGOV_TAG}"
      - docker build --build-arg BASE_IMAGE_TAG=$${XGOV_TAG} -t stp/forms-designer:$${DRONE_COMMIT_SHA} -t stp/forms-designer:latest designer/. --no-cache
      - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
      - aws ecr get-login-password --region $${AWS_REGION} | docker login --username AWS --password-stdin 340268328991.dkr.ecr.$${AWS_REGION}.amazonaws.com
      - docker image push stp/forms-designer:$${DRONE_COMMIT_SHA}
      - docker image push stp/forms-designer:latest
    volumes:
      - name: dockerclientconfig
        path: /root/.docker
    depends_on:
      - ecr-login
  - name: trigger dev deploy
    image: plugins/downstream
    settings:
      server: https://drone-gh.acp.homeoffice.gov.uk/
      deploy: development
      fork: true
      token:
        from_secret: downstream-trigger-token
      params:
        - SOURCE_HASH=${DRONE_COMMIT_HASH}
        - APP=digital-form-builder-designer
        - /drone/src/.env
      last_successful: true
      repositories:
        - UKHomeOffice/digital-form-builder-acp-deploy@main
    depends_on:
      - build and publish docker tag
services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

volumes:
  - name: dockerclientconfig
    temp: {}