kind: pipeline
name: code-analyze-check
type: kubernetes

trigger:
  branch: master
  event:
    - push
steps:
  - name: build
    pull: if-not-exists
    image: node:12.18.4-buster
    commands:
      - node -v
      - echo $(git log -1)
      - cat trigger.txt
      - export sha=$(tail -1 trigger.txt)
      - git clone https://github.com/XGovFormBuilder/digital-form-builder/
      - cd digital-form-builder
      - git checkout sha
      - git log -1
    when:
      branch:
        - master
      event:
        - push