kind: pipeline
name: code-analyze-check
type: kubernetes

trigger:
  branch: main
  event:
    - push
steps:
  - name: build
    pull: if-not-exists
    image: node:12.18.4-buster
    commands:
      - node -v
      - cat trigger.txt
    when:
      branch:
        - main
      event:
        - push