kind: pipeline
name: code-analyze-check
type: kubernetes

trigger:
  branch: main
  event:
    - tag
steps:
  - name: checkout code from xgov
    image: alpine/git
    commands:
      - git clone https://github.com/XGovFormBuilder/digital-form-builder/
      - source .env
      - cd digital-form-builder
      - git checkout $XGOV_SHA
      - cd ..
  - name: dev-run-tests-with-coverage
    pull: if-not-exists
    image: node:12.18.4-buster
    commands:
      - cd digital-form-builder
      - yarn
      - yarn build:dependencies
      - yarn test-cov
    depends_on:
      - checkout code from xgov
  - name: sonar_scan
    pull: if-not-exists
    image: quay.digital.homeoffice.gov.uk/ukhomeofficedigital/sonar-scanner-node:6a03c77c7e1bad005893cdcc9cd3d99479b79d5c
    commands:
      - cp sonar/sonar-project.properties digital-form-builder/
      - cp sonar/designer-sonar-project.properties digital-form-builder/designer/sonar-project.properties
      - cp sonar/model-sonar-project.properties digital-form-builder/model/sonar-project.properties
      - cp sonar/runner-sonar-project.properties digital-form-builder/runner/sonar-project.properties
      - pwd
      - ls -lah digital-form-builder/
      - sonar-scanner -Dsonar.projectVersion=${DRONE_BUILD_NUMBER} -Dsonar.projectBaseDir=digital-form-builder -Dsonar.projectKey=digital-form-builder
    depends_on:
      - dev-run-tests-with-coverage
  - name: slack-notification-code-check
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: stp-formbuilder-alerts
      template: >
        {{#success build.status}}
          Code Analysis succeeded. Good job.
          Build: {{build.number}}
          Author: {{build.author}}
          Link: {{build.link}}
        {{else}}
          Code Analysis failed. Fix me please.
          Build: {{build.number}}
          Author: {{build.author}}
          Link: {{build.link}}
        {{/success}}
    when:
      event:
        - tag
        - push
      status:
        - success
        - failure
    depends_on:
      - sonar_scan
---
kind: pipeline
name: designer
type: kubernetes
trigger:
  branch: main
  event:
    - tag
steps:
  - name: setup tags
    pull: if-not-exists
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    commands:
      - bin/designer.sh
  - name: publish to ecr
    image: plugins/ecr
    settings:
      access_key:
        from_secret: DESIGNER_REGISTRY_AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: DESIGNER_REGISTRY_AWS_SECRET_ACCESS_KEY
      region: eu-west-2
      repo: stp/forms-designer
      registry: 340268328991.dkr.ecr.eu-west-2.amazonaws.com
      dockerfile: designer/Dockerfile.out
    depends_on:
      - setup tags
  - name: slack-notification-designer-tagged
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: stp-formbuilder-alerts
      template: >
        {{#success build.status}}
          forms-designer Tagged. Good job.
          Build: {{build.number}}
          Author: {{build.author}}
          Link: {{build.link}}
        {{else}}
          forms-designer Tagging failed. Fix me please.
          Build: {{build.number}}
          Author: {{build.author}}
          Link: {{build.link}}
        {{/success}}
    when:
      event:
        - tag
        - push
      status:
        - success
        - failure
    depends_on:
      - publish to ecr
depends_on:
  - code-analyze-check

---
kind: pipeline
name: runner
type: kubernetes
trigger:
  branch: main
  event:
    - tag
steps:
  - name: setup tags
    pull: if-not-exists
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    commands:
      - bin/runner.sh
  - name: publish to ecr
    image: plugins/ecr
    settings:
      access_key:
        from_secret: RUNNER_REGISTRY_AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: RUNNER_REGISTRY_AWS_SECRET_ACCESS_KEY
      region: eu-west-2
      repo: stp/forms-runner
      registry: 340268328991.dkr.ecr.eu-west-2.amazonaws.com
      dockerfile: runner/Dockerfile.out
    depends_on:
      - setup tags
  - name: slack-notification-runner-tagged
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: stp-formbuilder-alerts
      template: >
        {{#success build.status}}
          forms-runner Tagged. Good job.
          Build: {{build.number}}
          Author: {{build.author}}
          Link: {{build.link}}
        {{else}}
          forms-runner Tagging failed. Fix me please.
          Build: {{build.number}}
          Author: {{build.author}}
          Link: {{build.link}}
        {{/success}}
    when:
      event:
        - tag
        - push
      status:
        - success
        - failure
    depends_on:
      - publish to ecr
depends_on:
  - code-analyze-check

---
kind: pipeline
name: deploy
type: kubernetes
trigger:
  branch: main
  event:
    - tag
steps:
  - name: setup deploy tags
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    commands:
      - bin/runner.sh
      - bin/designer.sh
  - name: trigger dev deploy
    image: plugins/downstream
    settings:
      server: https://drone-gh.acp.homeoffice.gov.uk/
      deploy: development
      fork: true
      token:
        from_secret: downstream-trigger-token
      params:
        - SOURCE_HASH=${DRONE_COMMIT_HASH}
        - /drone/src/.designer
        - /drone/src/.runner
        - /drone/src/.env
      last_successful: true
      repositories:
        - UKHomeOffice/digital-form-builder-acp-deploy@main
  - name: slack-notification-dev-deploy
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: stp-formbuilder-alerts
      template: >
        {{#success build.status}}
          Forms dev deployment triggered. Good job.
          Build: {{build.number}}
          Author: {{build.author}}
          Link: {{build.link}}
        {{else}}
          Forms dev deployment trigger failed. Fix me please.
          Build: {{build.number}}
          Author: {{build.author}}
          Link: {{build.link}}
        {{/success}}
    when:
      event:
        - tag
        - push
      status:
        - success
        - failure
    depends_on:
      - trigger dev deploy
depends_on:
  - designer
  - runner
