kind: pipeline
name: designer
type: kubernetes
trigger:
  branch: anchore-scan
  event:
    - push
steps:
  - name: pull image
    pull: if-not-exists
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    commands:
      - docker pull 340268328991.dkr.ecr.eu-west-2.amazonaws.com/stp/forms-designer:latest
    when:
      branch: anchore-scan
      event:
        - push
  - name: scan-image
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
    pull: always
    environment:
      IMAGE_NAME: stp/forms-designer:latest
      DOCKER_HOST: tcp://172.17.0.1:2375
    depends_on:
      - pull image
    when:
      branch: anchore-scan
      event:
        - push


services:
  - name: anchore-submission-server
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
    pull: always
    commands:
      - /run.sh server