kind: pipeline
name: code-analyze-check
type: kubernetes

trigger:
  branch: main
  event:
    - push
steps:
  - name: checkout code from xgov
      image: alpine/git
      commands:
        - git clone https://github.com/XGovFormBuilder/digital-form-builder/
        - source .env
        - cd digital-form-builder
        - git checkout $XGOV_SHA
        - cd ..
      volumes:
        - name: dockerclientconfig
          path: /root/.docker
      - name: dev-run-tests-with-coverage
        pull: if-not-exists
        image: node:12.18.4-buster
        commands:
          - cd digital-form-builder
          - yarn
          - yarn build:dependencies
          - yarn test-cov
        depends_on:
          - checkout code from xgov
        volumes:
          - name: dockerclientconfig
            path: /root/.docker
      - name: sonar_scan
        pull: if-not-exists
        image: quay.digital.homeoffice.gov.uk/ukhomeofficedigital/sonar-scanner-node:6a03c77c7e1bad005893cdcc9cd3d99479b79d5c
        commands:
          - cp sonar/sonar-project.properties digital-form-builder/
          - cp sonar/designer-sonar-project.properties digital-form-builder/designer/sonar-project.properties
          - cp sonar/model-sonar-project.properties digital-form-builder/model/sonar-project.properties
          - cp sonar/runner-sonar-project.properties digital-form-builder/runner/sonar-project.properties
          - pwd
          - ls -lah digital-form-builder/
          - sonar-scanner -Dsonar.projectVersion=${DRONE_BUILD_NUMBER} -Dsonar.projectBaseDir=digital-form-builder -Dsonar.projectKey=digital-form-builder
        depends_on:
          - dev-run-tests-with-coverage
---
kind: pipeline
name: designer
type: kubernetes
trigger:
  branch: main
  event:
    - push
    - tag
steps:
  - name: checkout code from xgov
    image: alpine/git
    commands:
      - git clone https://github.com/XGovFormBuilder/digital-form-builder/
  - name: setup tags
    pull: if-not-exists
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    commands:
      - bin/env.sh
    depends_on:
      - checkout code from xgov
  - name: publish to ecr
    image: plugins/ecr
    settings:
      access_key:
        from_secret: DESIGNER_REGISTRY_AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: DESIGNER_REGISTRY_AWS_SECRET_ACCESS_KEY
      region: eu-west-2
      repo: stp/forms-designer
      registry: 340268328991.dkr.ecr.eu-west-2.amazonaws.com
      dockerfile: designer/Dockerfile.out
      tags:
        - ${DRONE_COMMIT_SHA}
        - latest
    depends_on:
      - setup tags
  - name: trigger dev deploy
    image: plugins/downstream
    settings:
      server: https://drone-gh.acp.homeoffice.gov.uk/
      deploy: development
      fork: true
      token:
        from_secret: downstream-trigger-token
      params:
        - SOURCE_HASH=${DRONE_COMMIT_HASH}
        - APP=digital-form-builder-designer
        - /drone/src/.env
      last_successful: true
      repositories:
        - UKHomeOffice/digital-form-builder-acp-deploy@main
    depends_on:
      - publish to ecr
depends_on:
  - code-analyze-check