name: Anchore scan
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  runner-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Scan image
        uses: anchore/scan-action@v2
        with:
          image: "ghcr.io/xgovformbuilder/digital-form-builder-runner:latest"
          acs-report-enable: true
          fail-build: true
          severity-cutoff: critical
      - name: Upload artifact
          uses: actions/upload-artifact@v1.0.0
          if: always()
          with:
            name: AnchoreReports-Runner
            path: ./anchore-reports/
  designer-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Scan image
        uses: anchore/scan-action@v2
        with:
          image: "ghcr.io/xgovformbuilder/digital-form-builder-designer:latest"
          acs-report-enable: true
          fail-build: true
          severity-cutoff: critical
      - name: Upload artifact
          uses: actions/upload-artifact@v1.0.0
          if: always()
          with:
            name: AnchoreReports-Designer
            path: ./anchore-reports/