# This is a basic workflow that is manually triggered

name: Job Trigger by dispatch (from xgovformbuilder)

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'The SHA that triggered this build'
        required: false
      tag:
        required: false
        description: 'The tag that triggered this build'

jobs:
  xgovformbuilder-updated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checkout this repository
      - run: |
          XGOV_TAG=${{github.event.inputs.tag}}
          git fetch --prune --unshallow --tags
          echo ${XGOV_TAG}.$(git tag -l "$XGOV_TAG.*" | wc -l | xargs | awk '{print $1+1}')-acp
          echo "NEW_ACP_TAG=${XGOV_TAG}.$(git tag -l "$XGOV_TAG.*" | wc -l | xargs | awk '{print $1+1}')-acp" >> $GITHUB_ENV
          echo ${{github.event.inputs.branch}}
      - uses: actions/checkout@v2 # Checkout the xgov repository in /xgovformbuilder
        with:
          repository: XGovFormBuilder/digital-form-builder
          path: xgovformbuilder
          fetch-depth: 0
      - run: |
          echo "XGOV_REF=${{ github.event.client_payload.ref }}" > .env
          echo "XGOV_SHA=${{github.event.inputs.sha }}" >> .env
          echo "XGOV_TAG=${{github.event.inputs.tag }}" >> .env
      - name: Setup github user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Tag branch if triggered by a tag
        if: ${{github.event.inputs.tag != false || github.event.inputs.tag != 'false' }}
        #        run: echo "dummy tag ${{github.event.inputs.tag}}"
        run: |
          git add .
          git commit -m "$(git -C xgovformbuilder rev-list --pretty=oneline --max-count=1 ${{github.event.inputs.sha}})" --author="$(git -C xgovformbuilder rev-list --format="%an <%ae>" --max-count=1 ${{github.event.inputs.sha}} | sed '/^commit/d')"
          git tag ${NEW_ACP_TAG}
          git push --tags origin HEAD
        # The tag command will append an acp specific extension to the tag so that ACP can have separate changes not
        # related to the xgov-forms tagging e.g. xgov-forms tag 1.0.3-rc can have separate tag 1.0.3-rc.1-acp
      - name: Commit if changes to xgovformbuilder/digital-form-builder main
        if: ${{github.event.inputs.tag == false || github.event.inputs.tag == 'false'}}
        #        run: echo "dummy sha ${{github.event.inputs.sha}}"
        run: |
          git add .
          git commit -m "$(git -C xgovformbuilder rev-list --pretty=oneline --max-count=1 ${{github.event.inputs.sha}})" --author="$(git -C xgovformbuilder rev-list --format="%an <%ae>" --max-count=1 ${{github.event.inputs.sha}} | sed '/^commit/d')"
          git push -u
