# This is a basic workflow that is manually triggered

name: Job Trigger by dispatch (from xgovformbuilder)

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'The SHA that triggered this build'
        required: false
      tag:
        required: false
        description: 'The tag that triggered this build'

jobs:
  xgovformbuilder-updated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checkout this repository
      - uses: actions/checkout@v2 # Checkout the xgov repository in /xgovformbuilder
        with:
          repository: XGovFormBuilder/digital-form-builder
          path: xgovformbuilder
      - run: echo ${{ github.event.client_payload.ref }} > trigger.txt
      - run: echo ${{github.event.inputs.sha }} >> trigger.txt

      - name: Setup github user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Tag branch if triggered by a tag
        if: ${{github.event.inputs.tag != false }}
        #        run: echo "dummy tag ${{github.event.inputs.tag}}"
        run: |
          git tag ${{github.event.inputs.tag}}
          git push --tags origin HEAD

      - name: Commit if changes to xgovformbuilder/digital-form-builder master
        if: ${{github.event.inputs.tag == false}}
        #        run: echo "dummy sha ${{github.event.inputs.sha}}"
        run: |
          git add .
          git commit -m "$(git -C xgovformbuilder log --format="%H %s" ${{github.event.inputs.sha}})" --author="$(git -C xgovformbuilder log --format="%an <%ae>" ${{github.event.inputs.sha}})"
          git push -u